POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1dXNvIiwiaWQiOiI2MzU2ZDJiOWVlYTllZjM5NjRmNzkyYzgiLCJpYXQiOjE2NjY2MzYwNzksImV4cCI6MTY2NjYzOTY3OX0.kNwRzX6Rvf4I0vG5LAwlhCvMc38t3pTMBk5jvmrbaHc

{
  "title": "Testi2",
  "author": "Kalle2",
  "url": "google.com2",
  "likes": 42
}
