POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1dXNvIiwiaWQiOiI2MzU2ZDJiOWVlYTllZjM5NjRmNzkyYzgiLCJpYXQiOjE2NjY3MDk4MjAsImV4cCI6MTY2NjcxMzQyMH0.yqQVWIOvmRBcVAA1MkYyLWKKPADbnylyUniWIMNgyGQ

{
  "title": "Testi2",
  "author": "Kalle2",
  "url": "google.com2",
  "likes": 42
}
